#!/bin/sh
### BEGIN INIT INFO
# Provides:          scullmodules
# Required-Start:    $local_fs
# Required-Stop:
# Default-Start:     2 3 4 5
# Default-Stop:
# Short-Description: Load scull and misc-modules kernel modules
### END INIT INFO

case "$1" in
  start)
    echo "Loading scull and misc-modules..."
    insmod /lib/modules/$(uname -r)/extra/scull.ko || true
    for mod in /lib/modules/$(uname -r)/extra/*.ko; do
      [ "$mod" != "/lib/modules/$(uname -r)/extra/scull.ko" ] && insmod "$mod" || true
    done
    ;;
  stop)
    echo "Unloading scull and misc-modules..."
    rmmod scull || true
    # Unload other misc-modules if needed
    ;;
  *)
    echo "Usage: $0 {start|stop}"
    exit 1
    ;;
esac

exit 0

