#!/bin/sh
### BEGIN INIT INFO
# Provides:          S98miscmodules
# Required-Start:    $local_fs
# Required-Stop:
# Default-Start:     2 3 4 5
# Default-Stop:
# Short-Description: Load faulty kernel module
### END INIT INFO

case "$1" in
  start)
    echo "S98miscmodules script ran at $(date)" >> /var/log/miscmodules.log
    insmod /lib/modules/$(uname -r)/extra/faulty.ko >> /var/log/miscmodules.log 2>&1
    ;;
  stop)
    echo "Unloading faulty module..."
    rmmod faulty
    ;;
  restart)
    rmmod faulty
    modprobe faulty
    ;;
  *)
    echo "Usage: $0 {start|stop|restart}"
    exit 1
    ;;
esac

exit 0

